name: 'Release Canary Version'
description: 'Release a canary version (works with lerna publish only)'
author: 'Kamil Kisiela <kamil.kisiela@gmail.com>'
inputs:
  npm-token:
    description: 'NPM Auth Token'
  npm-script:
    description: 'NPM script that runs lerna publish'
    required: true
  changesets:
    description: 'Set to true if you are using changesets library for publish command'
    required: false
outputs:
  released:
    description: 'Released?'
  version:
    description: 'Version number'
  changesetsPublishedPackages:
    description: 'List of published packages and the new version'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'  
  color: 'purple'
